name: CI

on:
  # pushes to any branch
  push:
  # prs to master
  pull_request:
    branches: [ master ]
  # manually
  workflow_dispatch:

jobs:
  test:
    # i don't care enough to test on multiple platforms or multiple impls
    runs-on: ubuntu-latest
    steps:
      - name: checkout generator
        uses: actions/checkout@v2
        with:
          repository: gefjon/generator
          path: gefjon/generator
      - uses: gefjon/github-action-lisp-ci@v1
        with:
          system-name: 'immutable-vector'
          test-system-name: 'immutable-vector/test'
